CREATE TABLE IF NOT EXISTS delivery_requests (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  pickup_name VARCHAR(160) NOT NULL,
  pickup_phone VARCHAR(40) NOT NULL,
  pickup_address TEXT NOT NULL,
  destination_name VARCHAR(160) NOT NULL,
  destination_phone VARCHAR(40) NOT NULL,
  destination_address TEXT NOT NULL,
  package_description VARCHAR(500) NOT NULL,
  package_size ENUM('SMALL','MEDIUM','LARGE') NOT NULL DEFAULT 'MEDIUM',
  delivery_type ENUM('STANDARD','SCHEDULED','INTERCITY') NOT NULL DEFAULT 'STANDARD',
  scheduled_at DATETIME NULL,
  quoted_fee DECIMAL(12,2) NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'GHS',
  status ENUM('PENDING_QUOTE','QUOTED','PAYMENT_PENDING','PAID','ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PENDING_QUOTE',
  payment_reference VARCHAR(120) NULL,
  rider_name VARCHAR(160) NULL,
  rider_phone VARCHAR(40) NULL,
  rider_vehicle VARCHAR(160) NULL,
  tracking_note VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_delivery_customer FOREIGN KEY (customer_id) REFERENCES users(id),
  CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  INDEX idx_delivery_customer (customer_id, created_at),
  INDEX idx_delivery_status (status, created_at),
  INDEX idx_delivery_payment (payment_reference)
);
