import { useEffect, useState } from 'react'
import AdminLayout from '../../components/admin/AdminLayout.jsx'
import Icon from '../../components/Icon.jsx'
import { api } from '../../services/api.js'

const statuses = ['ALL','OPEN','IN_PROGRESS','WAITING_CUSTOMER','RESOLVED','CLOSED']
const priorities = ['LOW','NORMAL','HIGH']

export default function AdminSupportPage() {
  const [tickets, setTickets] = useState([]), [selected, setSelected] = useState(null)
  const [status, setStatus] = useState('ALL'), [query, setQuery] = useState(''), [reply, setReply] = useState('')
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [saving, setSaving] = useState(false)

  async function load() { setLoading(true); setError(''); try { const r = await api.getAdminSupportTickets({ status, q: query.trim() }); setTickets(r.tickets || []) } catch(e) { setError(e.message || 'Could not load tickets') } finally { setLoading(false) } }
  useEffect(() => { const t=setTimeout(load, query ? 250 : 0); return () => clearTimeout(t) }, [status, query])
  async function open(id) { try { setSelected(await api.getAdminSupportTicket(id)) } catch(e) { setError(e.message || 'Could not open ticket') } }
  async function update(payload) { if (!selected) return; setSaving(true); try { await api.updateAdminSupportTicket(selected.ticket.id, payload); await open(selected.ticket.id); await load() } catch(e) { setError(e.message || 'Could not update ticket') } finally { setSaving(false) } }
  async function sendReply(e) { e.preventDefault(); if (!reply.trim() || !selected) return; setSaving(true); try { await api.replyAdminSupportTicket(selected.ticket.id, reply); setReply(''); await open(selected.ticket.id); await load() } catch(e) { setError(e.message || 'Could not send reply') } finally { setSaving(false) } }

  return <AdminLayout title="Customer Support">
    {error && <div className="mb-4 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-[240px] flex-1"><Icon name="search" size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-pb-gray-muted" /><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tickets, customers or emails…" className="w-full rounded-lg border border-pb-gray-border bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-pb-green" /></div>{statuses.map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${status===s?'bg-pb-navy text-white':'border border-pb-gray-border bg-white text-pb-gray-text'}`}>{s.replaceAll('_',' ')}</button>)}</div>
    <div className="grid gap-5 xl:grid-cols-[430px_minmax(0,1fr)]">
      <div className="overflow-hidden rounded-card border border-pb-gray-border bg-white shadow-card"><div className="border-b border-pb-gray-border p-4 font-bold text-pb-gray-text">Requests {loading ? '…' : `(${tickets.length})`}</div>{tickets.length===0&&!loading?<p className="p-5 text-sm text-pb-gray-muted">No support tickets match this filter.</p>:tickets.map(t=><button key={t.id} onClick={()=>open(t.id)} className={`block w-full border-b border-pb-gray-border p-4 text-left last:border-0 ${selected?.ticket?.id===t.id?'bg-pb-green-light/50':'hover:bg-pb-gray-bg'}`}><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold text-pb-green">{t.ticket_number}</span><span className="text-[10px] font-bold uppercase text-pb-gray-muted">{t.priority}</span></div><div className="mt-1 font-semibold text-pb-gray-text">{t.subject}</div><div className="mt-1 text-xs text-pb-gray-muted">{t.customer_name} · {t.status.replaceAll('_',' ')}</div><div className="mt-1 text-xs text-pb-gray-muted">Updated {new Date(t.updated_at).toLocaleString()}</div></button>)}</div>
      <div className="rounded-card border border-pb-gray-border bg-white shadow-card">{!selected?<div className="flex min-h-[420px] items-center justify-center p-8 text-center text-sm text-pb-gray-muted">Select a customer request to manage it.</div>:<><div className="border-b border-pb-gray-border p-5"><div className="text-xs font-semibold text-pb-green">{selected.ticket.ticket_number}</div><h2 className="mt-1 text-lg font-bold text-pb-gray-text">{selected.ticket.subject}</h2><p className="mt-1 text-sm text-pb-gray-muted">{selected.ticket.customer_name} · {selected.ticket.customer_email}{selected.ticket.order_number ? ` · Order ${selected.ticket.order_number}` : ''}</p><div className="mt-3 flex flex-wrap gap-2"><select disabled={saving} value={selected.ticket.status} onChange={e=>update({status:e.target.value, priority:selected.ticket.priority})} className="rounded-lg border border-pb-gray-border px-3 py-2 text-xs font-semibold"><option value="OPEN">OPEN</option><option value="IN_PROGRESS">IN PROGRESS</option><option value="WAITING_CUSTOMER">WAITING CUSTOMER</option><option value="RESOLVED">RESOLVED</option><option value="CLOSED">CLOSED</option></select><select disabled={saving} value={selected.ticket.priority} onChange={e=>update({status:selected.ticket.status, priority:e.target.value})} className="rounded-lg border border-pb-gray-border px-3 py-2 text-xs font-semibold">{priorities.map(p=><option key={p}>{p}</option>)}</select></div></div><div className="max-h-[440px] space-y-3 overflow-y-auto p-5">{selected.messages.map(m=><div key={m.id} className={`rounded-lg border p-3 ${m.sender_role==='ADMIN'?'border-pb-green/20 bg-pb-green-light/40':'border-pb-gray-border bg-white'}`}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="font-semibold text-pb-gray-text">{m.sender_role==='ADMIN'?'PowerBase Support':m.sender_name}</span><span className="text-pb-gray-muted">{new Date(m.created_at).toLocaleString()}</span></div><p className="whitespace-pre-wrap text-sm text-pb-gray-text">{m.body}</p></div>)}</div>{selected.ticket.status!=='CLOSED'&&<form onSubmit={sendReply} className="border-t border-pb-gray-border p-4"><div className="flex gap-2"><textarea required value={reply} onChange={e=>setReply(e.target.value)} rows={3} placeholder="Reply to customer…" className="min-w-0 flex-1 resize-none rounded-lg border border-pb-gray-border px-3 py-2 text-sm outline-none focus:border-pb-green"/><button disabled={saving} className="self-end rounded-lg bg-pb-green px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Reply</button></div></form>}</>}</div>
    </div>
  </AdminLayout>
}
